### PR TITLE
Modernize through stack.yaml & package.yaml.

### PR DESCRIPTION
**Pull request by kindaro**
Since I wanted to have this build with modern `stack` installation, I did some surgery on the metadata and thought why not share.

### CODE REVIEW

**Comment by isovector** [comment]
Thanks for sending this! 

A few questions: `package.yaml` is for `hpack`, right? Does it require having `hpack` installed, or is this functionality built into stack?

**Comment by kindaro** [comment]
I think it is built in by now. You kind of will have `hpack` installed, just internally to `stack`.

(See [this `stack` issue](https://github.com/commercialhaskell/stack/issues/3809))

**Comment by isovector** [comment]
Awesome, thanks!

**Comment by kindaro** [comment]
Not so awesome as I thought. There is a problem with this update that renders the package practically unusable.

The module `Diagrams.TwoD.Layout.Constrained` is present in this package, but it is also present in the package `diagrams-contrib`, which is listed in modern `stack` snapshots, and not identical to (I guess, newer than) the local module.

We cannot easily remove the local module: the interface is slightly different from the module from `diagrams-contrib`, so some other modules will break.

I went ahead, removed the local module and fixed the discrepancy in types so that everything compiles. But this modification led to some circuits rendering empty. Perhaps you would take a look?

[This is where I started. There's one simple test case.](https://github.com/kindaro/circuitry/tree/add-tests)
[This is where I am now, with the same test case.](https://github.com/kindaro/circuitry/tree/remove-diagrams)

You can run the test with `stack test`, or look at the source. It's really trivial.

**Comment by kindaro** [comment]
One possible reason for this failure is that the type of the function `Diagrams.TwoD.Layout.Constrained.layout` has changed. In the local module, it returned a tuple `(a, QDiagram)` while in `diagram-contrib` it is `QDiagram` alone. I have no idea what that `a` was, the types are a bit complicated. I simply cut the reference to it away. Maybe we should reinstate it.

This is the relevant diff:

```diff
@@ -30,8 +30,8 @@ type Circuit' s = Circuit s B Double Any
 runCircuit :: (C n m, Show n) => (forall s. Circuit s b n m a) -> QDiagram b V2 n m
 -- TODO(sandy): this is probably ok
 runCircuit (Circuit dsl) = let c      = execStateT dsl def
-                               (s, d) = C.layout $ unsafeCoerce c
-                            in d # view compose s
+                               d = C.layout $ unsafeCoerce c
+                            in d
 
 liftCircuit :: (C.Constrained s b n m) a -> Circuit s b n m a
 liftCircuit = Circuit . lift
```

**Comment by isovector** [comment]
Hmm, lame. At the time of writing, `Diagrams.TwoD.Layout.Constrained` wasn't released, so I got a copy of it from the nightly. I'm going to be out of town for the weekend, but can definitely take a look early next week. 

One solution for the near-term is to rename the local copy of that module and continue using it.

**Comment by isovector** [comment]
Yeah -- that's the problem. The `s` there is a [`CircuitState`](https://github.com/kindaro/circuitry/blob/add-tests/src/Circuitry/Types.hs#L27) which contains part of the diagram to draw. The new interface to `layout` means we can't pull things out of the `Constrained` monad, which I guess is where we were building that `CircuitState`.

**Comment by isovector** [comment]
I'm starting to remember how all of this works. `Circuitry.afterwards` allows you to run arbitrary `Endo`s on the final result of the constrained diagram. We use this, eg. for drawing wires once we've finalized where their nodes should be. Explains why your wire doesn't show up :)

The solution here is a little tricky. Due to the new type of `layout`, we can no longer run a `StateT s Constrained` and ever get any useful data out, so the solution is probably to instead run a `State (s, Constrained)` and manually lift the `Constrained` stuff into it. It's going to be a bit of an undertaking, but shouldn't be hard. 

I'm not going to get a chance to make this change today, but I can definitely get it done next week. That being said, feel free to tackle it if you're feeling plucky! The `Circuit` type is going to need to change to:

```haskell
newtype Circuit s b n m a = Circuit
    { unCircuit :: forall x. State (CircuitState s b n m, Constrained s b n m x) a
    }
```

and then just get it compiling from there!

**Comment by kindaro** [comment]
I'll see what I can do. Have a great weekend!

**Comment by kindaro** [comment]
I didn't get it anywhere yet. I familiarized myself with the code somewhat, and it looks like numerous changes are in order.

* The monad instance for `Circuit` can no more be derived (due to the presence of `RankNTypes`), so I will have to roll one out by hand.
* The aforementioned `afterwards` is amended by as little as another optics.
* `lift*` family troubles me. I don't know yet what will become of them, as there is no more notion of `lift`ing around to begin with.
* The host of little helpers will hopefully take care of themselves once the monadic infrastructure of `Circuit` is reinstated.

Perhaps it will be beneficial to separate the functions that directly depend on the inner workings of `Circuit` to their own module.

If all goes well, I will have it work before Friday.

**Comment by isovector** [comment]
I looked into implementing this today, looks like it's going to be hard enough that we should just request support from upstream `diagrams-contrib` in order to allow the old interface and keep everything spicy. I've gotten in touch with @byorgey via irc and we'll see what happens.

**Comment by isovector** [comment]
This should be fixed as of https://github.com/isovector/circuitry/commit/bdc486f8eef41123ab5cc823cb7b103ffc3e5261, as soon as fpcomplete's hackage mirror updates with the latest `diagrams-contrib-1.4.2`. Thanks again for looking into it :)

**Comment by kindaro** [comment]
We should probably state in `package.yaml` that the lower version bound upon `diagrams-contrib` is `1.4.2`.

**Pull request merged**
